---
- name: Insure instance is removed
  azure_rm_virtualmachine:
    name: "{{ instance.name }}"
    resource_group: "{{ instance.resource_group }}"
  register: result
- name: Launch instance
  azure_rm_virtualmachine:
     name: "{{ instance.name }}"
     resource_group: "{{ instance.resource_group }}"
     admin_username: "{{ instance.username }}"
     ssh_password_enabled: false
     ssh_public_keys:
       - path: "/home/{{ instance.username }}/.ssh/authorized_keys"
         key_data: "{{ ssh_key_contents }}"
     tags:
        purpose: "{{ instance.purpose }}"
     storage_account: "{{ instance.storage_account }}"
     vm_size: "{{ instance.size }}"   
     image:
        offer: "{{ instance.offer }}"
        publisher:  "{{ instance.publisher }}"
        sku: "{{ instance.sku }}"
        version: "{{ instance.version }}"
     open_ports: "{{ instance.open_ports }}"
