---
- name: Removing VMs and all resources
  azure_rm_virtualmachine:
    name: "{{ instance.name }}"
    resource_group: "{{ instance.resource_group }}"
    state: absent
    remove_on_absent:
        - network_interfaces
        - virtual_storage
        - public_ips
